import enumeration from '../util/enum';

export default enumeration(
  'INITIAL_LOAD_COMPLETE',
  'SET_RECIPE_SEARCH_TERM',
  'SET_INGREDIENT_SEARCH_TERM',
  'SET_SELECTED_INGREDIENT_TAGS',
  'SET_BASE_LIQUOR_FILTER',
  'SET_SELECTED_RECIPE_LIST',
  'RECIPES_LOADED',
  'SAVE_RECIPE',
  'DELETE_RECIPE'
);
