import enumeration from '../util/enum';

export default enumeration(
  'INITIAL_LOAD_COMPLETE',
  'SET_RECIPE_SEARCH_TERM',
  'SET_INGREDIENT_SEARCH_TERM',
  'SET_SELECTED_INGREDIENT_TAGS',
  'SET_BASE_LIQUOR_FILTER',
  'SET_SELECTED_RECIPE_LIST',
  'SET_RECIPE_IDS',
  'RECIPES_LOADED',
  'INGREDIENTS_LOADED',
  'INGREDIENT_GROUPS_LOADED',
  'SAVE_RECIPE',
  'DELETE_RECIPE',
  'TOGGLE_INGREDIENT_MENU',
  'FAVORITE_RECIPE',
  'UNFAVORITE_RECIPE'
);
