export const selectBaseLiquorFilter = (state) => state.filters.baseLiquorFilter;
export const selectRecipeSearchTerm = (state) => state.filters.recipeSearchTerm;
export const selectIngredientSearchTerm = (state) => state.filters.ingredientSearchTerm;
export const selectSelectedRecipeList = (state) => state.filters.selectedRecipeList;
export const selectSelectedIngredientTags = (state) => state.filters.selectedIngredientTags;
export const selectIngredientsByTag = (state) => state.ingredients.ingredientsByTag;
export const selectOrderedIngredientGroups = (state) => state.ingredients.orderedIngredientGroups;
export const selectRecipesById = (state) => state.recipes.recipesById;
export const selectFavoritedRecipeIds = (state) => state.recipes.favoritedRecipeIds;
